-- CRIAÇÃO DAS TABELAS --

create table usuarios (
   id       number
      generated by default on null as identity
   primary key,
   name     varchar2(150) not null,
   email    varchar2(130) unique not null,
   password varchar(150) not null
);

create table categorias (
   id   number
      generated by default on null as identity
   primary key,
   name varchar2(100) not null
);

create table transacoes (
   id          number primary key,
   user_id     number not null,
   category_id number not null,
   value       number(10,2) not null,
   date_time   date not null,
   description varchar2(200),
   constraint fk_usuarios_transacoes foreign key ( user_id )
      references usuarios ( id ),
   constraint fk_categorias_transacoes foreign key ( category_id )
      references categorias ( id )
);

create sequence seq_transacoes start with 1 increment by 1 nocache;

-- PROCEDURE PARA INSERÇÃO DA TRANSAÇÃO --

create or replace procedure new_transaction (
   p_user_id     in number,
   p_category_id in number,
   p_value       in number,
   p_date_time   in date,
   p_description in varchar2
) as
begin
   insert into transacoes (
      id,
      user_id,
      category_id,
      value,
      date_time,
      description
   ) values ( seq_transacoes.nextval,
              p_user_id,
              p_category_id,
              p_value,
              p_date_time,
              p_description );
end;